#! /bin/sh
#
# mkdeformvideo -- make the deform video
#
# (c) 2014 Prof Dr Andreas Mueller, Hochschule Rapperswil
#

cd def || exit 1

if true
then
	for filename in *.mp
	do
		b=`basename ${filename} .mp`
		TEX=latex mpost ${filename}
		mpname=${b}.1
		mptopdf ${mpname}
		pdfname=${b}-1.pdf
		jpgname=${b}.jpg
		gs -sDEVICE=jpeg -dBATCH -q -dNOPAUSE -r229 -g1024x624 \
				-sOutputFile=${jpgname} ${pdfname}
	done
fi

jpeg2yuv -j i%04d.jpg -f 25 -I p -L 0 | \
	mpeg2enc -f 9 --no-constraints -b 15000 -o deform.mpg
